<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Datasiswa_model extends CI_Model
{

    public $table = 't_siswa';
    public $id = 'id_siswa';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables list siswa
    function json() {
        $this->datatables->select('id_siswa,t_siswa.id_pendaftaran,nis,t_siswa.nisn,t_siswa.nama_siswa,t_ppdb.alamat,t_ppdb.tempat_lahir,t_ppdb.tanggal_lahir,t_ppdb.asal_sekolah,t_ppdb.nama_wali,t_siswa.id_kelas,t_siswa.status_aktif');
        $this->datatables->from('t_siswa');
        //add this line for join
        $this->datatables->join('t_ppdb', 't_siswa.id_pendaftaran = t_ppdb.id_pendaftaran');
        //$this->datatables->where('status_aktif','Aktif');
        $this->datatables->add_column('action', anchor(site_url('datasiswa/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
            ".anchor(site_url('datasiswa/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
                ".anchor(site_url('datasiswa/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_siswa');
        return $this->datatables->generate();
    }

    //data tabel mutasi siswa
    function jsonmutasi()
    {
        $this->datatables->select('id_siswa,t_siswa.id_pendaftaran,nis,t_siswa.nisn,t_siswa.nama_siswa,t_ppdb.alamat,t_ppdb.tempat_lahir,t_ppdb.tanggal_lahir,t_ppdb.asal_sekolah,t_ppdb.nama_wali,t_siswa.id_kelas,t_siswa.status_aktif');
        $this->datatables->from('t_siswa');
        //add this line for join
        $this->datatables->join('t_ppdb', 't_siswa.id_pendaftaran = t_ppdb.id_pendaftaran');
        $this->datatables->add_column('action', anchor(site_url('datasiswa/pindah/$1'),'<i class="fa fa-eye" aria-hidden="true"> Pindah</i>', 'class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ? \')"'),'id_siswa');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
       //$this->db->join('t_ppdb','t_siswa.id_pendaftaran=t_ppdb.id_ppdb');
        return $this->db->get($this->table)->result();
    }

    function get_all_join()
    {
        $this->db->select('*');
        $this->db->from('t_siswa');
        $this->db->join('t_ppdb','t_siswa.id_pendaftaran=t_ppdb.id_pendaftaran');
        return $this->db->get()->result();

    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_siswa', $q);
	$this->db->or_like('id_pendaftaran', $q);
	$this->db->or_like('nisn', $q);
	$this->db->or_like('nama_siswa', $q);
	$this->db->or_like('id_kelas', $q);
	$this->db->or_like('status_aktif', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_siswa', $q);
	$this->db->or_like('id_pendaftaran', $q);
	$this->db->or_like('nisn', $q);
	$this->db->or_like('nama_siswa', $q);
	$this->db->or_like('id_kelas', $q);
	$this->db->or_like('status_aktif', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Datasiswa_model.php */
/* Location: ./application/models/Datasiswa_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-04-21 22:22:34 */
/* http://harviacode.com */