<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Datamatapelajaran_model extends CI_Model
{

    public $table = 't_matpel';
    public $id = 'id_matpel';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_matpel,nama_matpel,id_guru,semester,tahun_ajaran_mulai,tahun_ajaran_selesai');
        $this->datatables->from('t_matpel');
        //add this line for join
        //$this->datatables->join('table2', 't_matpel.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('datamatapelajaran/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
            ".anchor(site_url('datamatapelajaran/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
                ".anchor(site_url('datamatapelajaran/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_matpel');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_matpel', $q);
	$this->db->or_like('nama_matpel', $q);
	$this->db->or_like('id_guru', $q);
	$this->db->or_like('semester', $q);
	$this->db->or_like('tahun_ajaran_mulai', $q);
	$this->db->or_like('tahun_ajaran_selesai', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_matpel', $q);
	$this->db->or_like('nama_matpel', $q);
	$this->db->or_like('id_guru', $q);
	$this->db->or_like('semester', $q);
	$this->db->or_like('tahun_ajaran_mulai', $q);
	$this->db->or_like('tahun_ajaran_selesai', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Datamatapelajaran_model.php */
/* Location: ./application/models/Datamatapelajaran_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-04-28 21:42:35 */
/* http://harviacode.com */