<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Nilai_model extends CI_Model
{

    public $table = 't_nilai';
    public $id = 'id_nilai';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_nilai,id_siswa,id_matpel,nilai_absensi,nilai_tugas,nilai_kuis,nilai_uts,nilai_uas,niali_akhir');
        $this->datatables->from('t_nilai');
        //add this line for join
        //$this->datatables->join('table2', 't_nilai.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('datanilai/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
            ".anchor(site_url('datanilai/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
                ".anchor(site_url('datanilai/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_nilai');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_nilai', $q);
	$this->db->or_like('id_siswa', $q);
	$this->db->or_like('id_matpel', $q);
	$this->db->or_like('nilai_absensi', $q);
	$this->db->or_like('nilai_tugas', $q);
	$this->db->or_like('nilai_kuis', $q);
	$this->db->or_like('nilai_uts', $q);
	$this->db->or_like('nilai_uas', $q);
	$this->db->or_like('niali_akhir', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_nilai', $q);
	$this->db->or_like('id_siswa', $q);
	$this->db->or_like('id_matpel', $q);
	$this->db->or_like('nilai_absensi', $q);
	$this->db->or_like('nilai_tugas', $q);
	$this->db->or_like('nilai_kuis', $q);
	$this->db->or_like('nilai_uts', $q);
	$this->db->or_like('nilai_uas', $q);
	$this->db->or_like('niali_akhir', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
    //get data
    function show_data_siswa()
    {
        $this->db->select("*");
        $this->db->from('t_siswa');
        return $this->db->get()->result();
    }
    function show_data_matpel()
    {
        $this->db->select("*");
        $this->db->from('t_matpel');
        return $this->db->get()->result();
    }

}

/* End of file Nilai_model.php */
/* Location: ./application/models/Nilai_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-07-03 05:35:54 */
/* http://harviacode.com */